{% set version = "1.0.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-syuzhet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/syuzhet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/syuzhet/syuzhet_{{ version }}.tar.gz
  sha256: af4f2b4c4580a94c0a07e37db9e9e29c072e314990dcdee420c8580e4d78f232

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-nlp
    - r-dplyr
    - r-dtt
    - r-textshape >=1.3.0
    - r-tidyr
    - r-zoo
  run:
    - r-base
    - r-nlp
    - r-dplyr
    - r-dtt
    - r-textshape >=1.3.0
    - r-tidyr
    - r-zoo

test:
  commands:
    - $R -e "library('syuzhet')"           # [not win]
    - "\"%R%\" -e \"library('syuzhet')\""  # [win]

about:
  home: https://github.com/mjockers/syuzhet
  license: GPL-3.0-only
  summary: Extracts sentiment and sentiment-derived plot arcs from text using a variety of sentiment dictionaries conveniently packaged for consumption by R users.  Implemented dictionaries include "syuzhet" (default) developed in the Nebraska Literary Lab "afinn" developed by Finn {\AA}rup Nielsen, "bing" developed by Minqing
    Hu and Bing Liu, and "nrc" developed by Mohammad, Saif M. and Turney, Peter D. Applicable references are available in README.md and in the documentation for the "get_sentiment" function.  The package also provides a hack for implementing Stanford's coreNLP sentiment parser. The package provides several methods for plot
    arc normalization.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH
