# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "M8vi54r0cZjZ9kyNlbWLvCMg/pdyvxgqrXKrwY+7HAGSJNTX6RONdAQD5zh5mStuz0Xp94RsSUiyi2oxE++EUt6A66tzOJVsXTEICaDnJ6ER4i5CEkmVn2TdldsJVWg1DR3fUcJO2ZtCyWv9q59ZVIkS/aMTrjATk3nLergTwj5mBjJc8N6MtwxZ5svuxMYWwbpops3KTg9FYp0+8Hi5hMUUnEGE72BCK3w9jHUVCpf49B8tK6RGWKtSYqR+uQxX1syl3shf7xi3sa05RGlGq0i6pcLHrrj50EYM5/35TnnO2EGnGZHvn+qoHr1UmuxPH7/1VfnC95uaP5/BDMN/kBvlddeK6RaUYFBXPafCyIAbNnt2zw/SR1zARpEhO+QsPWXr18cIrQFF9R5Gcr1yKUbUkDCFTF7y6PUuTECqBarxAp1ZCUjUAXIvZywjPffIIiodENCl4c37M2N13EGXho+MXLG9iZ0/4kuxMcq34pJzlxzhXobbnWsKcSIqU1c8tjTTvWaBphBaIL2Tcdr9NLwEsi20bxvrlb+BJ8mQKegYDovrstsA7p8/CBCQnOBdj/9NYo6PnZJzFLq1Hv2VQuRhWNswPfm13+TY1/BkGSmxFd77bZLvwWWP4gHnsJo3xq2CMzfLak/K2hHIyE8BkkO1HdPLHM8UqTGyp3RQHmE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
