travis:
  secure:
    BINSTAR_TOKEN: ZPXgFTYlkQSkTJn3ujYFJUQnhjeG6qhLX8m2dkykO3XzUCrOj37FGP/8vKXGmj8Z108sfnrauBFydVeW4kYZdI6Q+50U/66sWQMeWbgc/TL9Xp/Pqo0Q1T1UYtregHwhfSs/NXyiEnAwxiuPjab94fUP92UupUtefNXDTJK6oCUwxDn3iQTjCrTuWZW0jYmmqcBJNW5lgbCXHG9u5XsUP1ffJkwVja1dVbavgexKL8fShXPENoAa3RsMA7asYGPxT86RIYEhBMuf+2pXXHmwaazFJBzHoivl3Iu54AeYDZR5svZWK/U+PzPUFUD0CcTjoelwHaAfAldQuLHapWWf4b0Sy2Oi5mcr8H7XHHY22JBh3K7a5VTYLZkGjZqCTnEivEt/mKEdzmIQyV7lsJCuX7CpnrfUh2L/pOdoz9CWpoLvhqLsWM7EFFTdG0JalSlMh71oLT/w43MKHtEW1AoPyRujxV3Oc1pEpXQ2hz7L1tWpSFF+Pi1uqw0zUvawSZeQDahjv6QJE2+EM6hMRednHU+kchofVe+aMsrSBtqM5UAwlmBmpl3iM7A857h7FN1AKtZHH3dTqmD9uGNJqhXCVPI8xbepj+4Y5ATZMzbLcP/BNoV44B4sN0sEwA7ZvBIRyWy1R6Y/aMgG7yoXhSWs2manLd10qDTZrLh/vmVLPIg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
