travis:
  secure:
    BINSTAR_TOKEN: M8vi54r0cZjZ9kyNlbWLvCMg/pdyvxgqrXKrwY+7HAGSJNTX6RONdAQD5zh5mStuz0Xp94RsSUiyi2oxE++EUt6A66tzOJVsXTEICaDnJ6ER4i5CEkmVn2TdldsJVWg1DR3fUcJO2ZtCyWv9q59ZVIkS/aMTrjATk3nLergTwj5mBjJc8N6MtwxZ5svuxMYWwbpops3KTg9FYp0+8Hi5hMUUnEGE72BCK3w9jHUVCpf49B8tK6RGWKtSYqR+uQxX1syl3shf7xi3sa05RGlGq0i6pcLHrrj50EYM5/35TnnO2EGnGZHvn+qoHr1UmuxPH7/1VfnC95uaP5/BDMN/kBvlddeK6RaUYFBXPafCyIAbNnt2zw/SR1zARpEhO+QsPWXr18cIrQFF9R5Gcr1yKUbUkDCFTF7y6PUuTECqBarxAp1ZCUjUAXIvZywjPffIIiodENCl4c37M2N13EGXho+MXLG9iZ0/4kuxMcq34pJzlxzhXobbnWsKcSIqU1c8tjTTvWaBphBaIL2Tcdr9NLwEsi20bxvrlb+BJ8mQKegYDovrstsA7p8/CBCQnOBdj/9NYo6PnZJzFLq1Hv2VQuRhWNswPfm13+TY1/BkGSmxFd77bZLvwWWP4gHnsJo3xq2CMzfLak/K2hHIyE8BkkO1HdPLHM8UqTGyp3RQHmE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
